export default{
    LOGIN:"LOGIN",
    SIGNUP:"SIGNUP",
    ONBOARDING:"ONBOARDING",
    HOME:"HOME",
    REMINDER:"REMINDER",
    BTM:"BTM",
    CLOCK:"CLOCK",
    CALENDER:"CALENDER",
    PROFILE:"PROFILE"
}