export default{
    LOGIN:"LOGIN",
    SIGNUP:"SIGNUP",
    ONBOARDING:"ONBOARDING",
    HOME:"HOME",
    REMINDER:"REMINDER",
    BTM:"BTM",
    POST:"POST",
    CALENDER:"CALENDER",
    PROFILE:"PROFILE",
    ITEM_DETAILS:"ITEM_DETAILS",
    GOOGLE_SIGNIN:"GoogleSignIn",
    FACEBOOK_SIGNIN:"FacebookSignIn"
}